### ISSUE TITLE
ecu.test-Executable cannot be found 

### ISSUE THREAD

**Issue by GeneralMidiRotkiv** [jenkinsci/ecu-test-execution-plugin#149]
### Describe the bug

I am in the process of switching from the old version of the plugin to this one. While the old plugin works as expected, the new version does not seem to find the executable in the filepath provided by me. Every time I start the job I get the following error: 

org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 9ae0d12b-bafa-4bce-99fa-b614b191e89a
12:51:46  java.lang.IllegalArgumentException: Tool executable path of 'ecu.test2': 'C:\Program Files\ecu.test BMW 2024.2' does not contain a tracetronic tool!

However, the provided path is the same as the one the old plugin is using, working fine

### Steps to reproduce

Install Jenkins version 2.452.1 and the ecu.test execution plugin. In the "Tools" setting, set the path to the ecu.test executable and run a basic pipeline (e.g ttStartTool)

### Expected behavior

Jenkins should be able to start ecu.test on the machine

### Versions

- Jenkins: 2.452.1
- Plugin: 3.4
- ecu.test: BMW 2024.2
- test.guide: n/a

**Comment by ErikRehmTT** [comment]
Derived a new issue from it. So will close this bug.
