### ISSUE TITLE
Integrate CodeNarc Check

### ISSUE THREAD

**Issue by TT-S3-D1** [jenkinsci/ecu-test-execution-plugin#18]
### Describe the feature request

As a maintainer I want to improve the code quality by highlighting issues with automated static code analysis and architectural tests.

### Upstream changes

* [ ] build.gradle
* [ ] new codenarc.groovy
* [ ] code changes if necessary

### Acceptance criteria

* [ ] define ruleset for CodeNarc
* [ ] activate in build.gradle with seperate phase
* [ ] prepare CodeNarc check in CI
* [ ] fix all findings

**Comment by ErikRehmTT** [comment]
Old Issue. Codenarc already got integrated in the past. -> closing the issue
